/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CurrentToast`; params?: Router.UnknownInputParams; } | { pathname: `/Provider`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AddScores` | `/AddScores`; params?: Router.UnknownInputParams; } | { pathname: `/components/Leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/components/LeagueName`; params?: Router.UnknownInputParams; } | { pathname: `/components/OfficialRounds`; params?: Router.UnknownInputParams; } | { pathname: `/components/PlayerCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/RoundCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddScores`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddScores/SelectGolfCourse`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddScores/EnterPlayerScores`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddScores/ConfirmRoundSubmit`; params?: Router.UnknownInputParams; } | { pathname: `/api/getPlayersByLeague`; params?: Router.UnknownInputParams; } | { pathname: `/api/getLeagueRounds`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/CurrentToast`; params?: Router.UnknownOutputParams; } | { pathname: `/Provider`; params?: Router.UnknownOutputParams; } | { pathname: `/modal`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/AddScores` | `/AddScores`; params?: Router.UnknownOutputParams; } | { pathname: `/components/Leaderboard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/LeagueName`; params?: Router.UnknownOutputParams; } | { pathname: `/components/OfficialRounds`; params?: Router.UnknownOutputParams; } | { pathname: `/components/PlayerCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/RoundCard`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AddScores`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AddScores/SelectGolfCourse`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AddScores/EnterPlayerScores`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AddScores/ConfirmRoundSubmit`; params?: Router.UnknownOutputParams; } | { pathname: `/api/getPlayersByLeague`; params?: Router.UnknownOutputParams; } | { pathname: `/api/getLeagueRounds`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/CurrentToast${`?${string}` | `#${string}` | ''}` | `/Provider${`?${string}` | `#${string}` | ''}` | `/modal${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/AddScores${`?${string}` | `#${string}` | ''}` | `/AddScores${`?${string}` | `#${string}` | ''}` | `/components/Leaderboard${`?${string}` | `#${string}` | ''}` | `/components/LeagueName${`?${string}` | `#${string}` | ''}` | `/components/OfficialRounds${`?${string}` | `#${string}` | ''}` | `/components/PlayerCard${`?${string}` | `#${string}` | ''}` | `/components/RoundCard${`?${string}` | `#${string}` | ''}` | `/components/AddScores${`?${string}` | `#${string}` | ''}` | `/components/AddScores/SelectGolfCourse${`?${string}` | `#${string}` | ''}` | `/components/AddScores/EnterPlayerScores${`?${string}` | `#${string}` | ''}` | `/components/AddScores/ConfirmRoundSubmit${`?${string}` | `#${string}` | ''}` | `/api/getPlayersByLeague${`?${string}` | `#${string}` | ''}` | `/api/getLeagueRounds${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/CurrentToast`; params?: Router.UnknownInputParams; } | { pathname: `/Provider`; params?: Router.UnknownInputParams; } | { pathname: `/modal`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/AddScores` | `/AddScores`; params?: Router.UnknownInputParams; } | { pathname: `/components/Leaderboard`; params?: Router.UnknownInputParams; } | { pathname: `/components/LeagueName`; params?: Router.UnknownInputParams; } | { pathname: `/components/OfficialRounds`; params?: Router.UnknownInputParams; } | { pathname: `/components/PlayerCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/RoundCard`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddScores`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddScores/SelectGolfCourse`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddScores/EnterPlayerScores`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddScores/ConfirmRoundSubmit`; params?: Router.UnknownInputParams; } | { pathname: `/api/getPlayersByLeague`; params?: Router.UnknownInputParams; } | { pathname: `/api/getLeagueRounds`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
